export const UPD_CUSTOMER_NAME = 'UPD_CUSTOMER_NAME';
export const UPD_CUSTOMER_PHONE = 'UPD_CUSTOMER_PHONE';
export const UPD_CUSTOMER_EMAIL = 'UPD_CUSTOMER_EMAIL';
export const UPD_CUSTOMER_ADDRESS = 'UPD_CUSTOMER_ADDRESS';

export const UPD_DELIVERY_DATE = 'UPD_DELIVERY_DATE';
export const UPD_DELIVERY_TIME = 'UPD_DELIVERY_TIME';

export const UPD_BIG_BOTTLE_COUNT = 'UPD_BIG_BOTTLE_COUNT';
export const UPD_MIDDLE_BOTTLE_COUNT = 'UPD_MIDDLE_BOTTLE_COUNT';
export const UPD_SMALL_BOTTLE_COUNT = 'UPD_SMALL_BOTTLE_COUNT';
